name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - "dependencies"
  - "skip-changelog"
version-resolver:
  major:
    labesl:
      - "breaking_change"
  minor:
    labels:
      - "enhancement"
  default: patch
categories:
  - title: "Features"
    labels:
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "⚠️ Breaking changes"
    label: "breaking-change"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
